services:
  authdb:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - 5432:5432
    volumes:
      - authdb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: bizno-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bizno-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    container_name: bizno-nats
    ports:
      - "4222:4222"   # porta dos clientes (auth-service, notification-service)
      - "8222:8222"   # porta de monitorização (dashboard)
    networks:
      - bizno-network

volumes:
  authdb_data:
  redis_data:

networks:
  bizno-network:
    driver: bridge