app:
  secret-key: aHNoZ2Rqc2FmZGpnZmdzYXNmbGpzYWZhc2ZhYml6bm8yMDI2bWFya2V0cGxhY2U=
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: false
  grpc:
    server:
      port: 9091
      reflection:
        enabled: true
management:
  server:
    port: 9081
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
loki:
  url: ${LOKI_URL:http://localhost:3100}