name: Auth Service CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    uses: bizno-marketplace/.github/.github/workflows/ci-reusable.yml@master
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-bdd-tests: true
      run-coverage: true
      coverage-threshold: 40